name: Artifact Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      
jobs:
  steps:
    - name: upload artifact
    - uses: actions/checkout@v3

    - run: mkdir -p /artifact

    - run: echo hello > path/to/artifact/world.txt

    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: /world.txt
